config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    authenticated :user do
      root 'users#me', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :zones
  resources :routes
  resources :trip_notices, except: :index do
    get 'search', on: :collection
    get 'send_mail', on: :member
  end
  resources :users do
    collection do
      get 'me'
      resource :medical_record, path: 'me/medical_record'
    end
  end

end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :user
  has_many :medical_conditions, dependent: :destroy

  enum blood_type: [:o_positive, :o_negative, :a_positive, :a_negative,
                    :b_positive, :b_negative, :ab_positive, :ab_negative]

  accepts_nested_attributes_for :medical_conditions, allow_destroy: true

end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @medical_record = MedicalRecord.new
    @medical_record.medical_conditions.build
  end

  def edit
  end

  def create
    @medical_record = MedicalRecord.new(medical_record_params)
    @medical_record.user = current_user
    if @medical_record.save
      redirect_to me_users_url, anchor: 'medical_record', notice: 'Ficha médica fue creada exitosamente.'
    else
      render :new
    end
  end

  def update
    if @medical_record.update(medical_record_params)
      redirect_to me_users_url, anchor: 'medical_record', notice: 'Ficha médica fue actualizada exitosamente.'
    else
      render :edit
    end
  end

  def destroy
    @medical_record.destroy
    redirect_to me_users_url, anchor: 'medical_record', notice: 'Ficha médica fue eliminada exitosamente.'
  end

  private

  def medical_record_params
    params.require(:medical_record)
          .permit(:blood_type, :medical_insurance, :health_insurance,
                  :prefered_medical_center, medical_conditions_attributes: [:id,
                  :name, :risk, :medicine, :dose, :frequency, :side_effects,
                  :comment, :_destroy])
  end

  def set_medical_record
    @medical_record = current_user.medical_record
  end
end

app/views/medical_records/_form.html.erb
<div class="form-group row multiple-form-group itinerary" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :blood_type, collection: MedicalRecord.blood_types.collect { |bt| [MedicalRecord.human_attribute_name("blood_type.#{bt[0]}"), bt[0]] },
      input_html: { class: 'form-control ctype' }, label: false, prompt: 'Tipo de sangre' %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :prefered_medical_center, input_html: { class: 'form-control',
      placeholder: 'Centro médico preferido' }, label: false, required: true %>
  </div>
</div>
<div class="form-group row multiple-form-group itinerary" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :medical_insurance, input_html: { class: 'form-control',
      placeholder: 'Previsión médica' }, label: false, required: true %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :health_insurance, input_html: { class: 'form-control',
      placeholder: 'Seguro médico' }, label: false, required: true %>
  </div>
</div>
<h3>Condiciones médicas</h3>
<div class="panel panel-default">
  <%= f.simple_fields_for :medical_conditions do |mc| %>
    <div class="form-group row multiple-form-group medical" style="padding:10px;margin:0">
      <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
          <%= mc.input :name, input_html: { class: 'form-control name',
            placeholder: 'Nombre' }, label: false, required: true %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <%= mc.input :risk, input_html: { class: 'form-control risk',
            rows: 5, placeholder: 'Describa el riesgo que implica para la actividad' },
            label: false, required: true %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
          <div class="row">
            <%= mc.input :medicine, input_html: { class: 'form-control medicine',
              placeholder: 'Medicamento' }, label: false, required: true %>
          </div>
          <div class="row">
            <%= mc.input :dose, input_html: { class: 'form-control dose',
              placeholder: 'Dosis/Frecuencia' }, label: false, required: true %>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <%= mc.input :side_effects, input_html: { class: 'form-control side-effects',
            rows: 5, placeholder: 'Efectos secundarios' },
            label: false, required: true %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
          <%= mc.input :comment, input_html: { class: 'form-control comment',
            rows: 5, placeholder: 'Comentarios' },
            label: false, required: true %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1" style="padding: 0">
        <span class="input-group-btn text-left">
          <button type="button" class="btn btn-default btn-add">+</button>
        </span>
        <span class="input-group-btn text-right">
          <button type="button" class="btn btn-danger btn-remove">–</button>
        </span>
      </div>
    </div>
  <% end %>
</div>
<div class="form-actions row">
  <div class="col-md-5">
    <%= f.submit 'Guardar', class: 'btn btn-success' %>
  </div>
</div>

app/views/medical_records/edit.html.erb
<%= link_to 'Atrás', :back, class: 'btn btn-default' %>
<h1 class="text-center">Editar ficha médica</h1>

<div style="width:90%;margin:auto">
  <%= simple_form_for(@medical_record, url: medical_record_path) do |f| %>
    <%= f.error_notification %>
    <%= render 'form', f:f %>
  <% end %>
</div>

app/views/medical_records/new.html.erb
<%= link_to 'Atrás', :back, class: 'btn btn-default' %>
<h1 class="text-center">Nueva ficha médica</h1>

<div style="width:90%;margin:auto">
  <%= simple_form_for(@medical_record, url: medical_record_path) do |f| %>
    <%= f.error_notification %>
    <%= render 'form', f:f %>
  <% end %>
</div>