config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    authenticated :user do
      root 'users#me', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :zones
  resources :routes
  resources :trip_notices, except: :index do
    get 'search', on: :collection
    get 'send_mail', on: :member
  end
  resources :users do
    collection do
      get 'me'
      resource :medical_record, path: 'me/medical_record'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :medical_record
  has_and_belongs_to_many :trip_notices
  has_many :trip_conveyances
  has_many :supervised_trip_notices, class_name: 'TripNotice'
  has_one :emergency_contact, class_name: 'Contact', as: :contactable, dependent: :destroy

  enum role: [:member, :external, :admin]
  enum gender: [:male, :female]

  has_attached_file :avatar, styles: { medium: '150x150' }
  validates_attachment :avatar, content_type: { content_type: /\Aimage\/.*\z/ }

  validates :first_name, :last_name, presence: true
  # validates :member_number, uniqueness: true, if: :member?

  accepts_nested_attributes_for :emergency_contact, allow_destroy: true

  before_validation :generate_password, on: :create

  def member?
    self.role == 'member'
  end

  def generate_password
    if password.blank?
      self.password = Devise.friendly_token.first(8)
      UserMailer.welcome_email(self, password).deliver_now
    end
  end

  def active_for_authentication?
    super && self.active
  end

  def inactive_message
    "Lo sentimos, su usuario ha sido desactivado."
  end

  def image
    avatar.present? ? avatar(:medium) : 'default-profile.jpg'
  end

  def age
    return 'Desconocida' if birthday.nil?
    today ||= Date.current
    diff = (12 * today.year + today.month) - (12 * birthday.year + birthday.month)
    y, m = diff.divmod 12
    y == 1 ? '1 año' : "#{y} años"
  end

  def seniority
    return '' if date_of_joining.nil?
    year = ' hace '
    months = ' hace '
    years = Date.current.year - date_of_joining.year
    if years == 0
      months = Date.current.month - date_of_joining.month
    else
      years
    end
  end

  def full_name
    last_name.titleize + ', ' + first_name.titleize
  end

  def full_name2
    first_name.titleize + ' ' + last_name.titleize
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order(last_name: :asc)
  end

  def show
    if @user.id == current_user.id
      redirect_to me_users_url
    else
      render action: :me
    end
  end

  def me
    @user = current_user
    @user = User.find(params[:id]) if params[:id].present?
    @trip_notices = @user.trip_notices.order(updated_at: :desc)
  end

  def new
    @user = User.new
    @user.build_emergency_contact unless @user.emergency_contact.present?
  end

  def edit
    @user.build_emergency_contact unless @user.emergency_contact.present?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to me_users_url, notice: 'Usuario fue creado exitosamente.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to me_users_url, notice: 'Usuario fue actualizado exitosamente.'
    else
      puts ap @user.errors.messages
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuario fue eliminado exitosamente.'
  end

  private

  def user_params
    if current_user.member?
      params.require(:user)
            .permit(:id, :first_name, :last_name, :phone, :birthday, :gender,
                    :avatar, emergency_contact_attributes: [:id, :name, :email,
                    :phone, :additional_phone, :_destroy])
    elsif current_user.admin?
      params.require(:user)
            .permit(:id, :first_name, :last_name, :phone, :birthday, :gender,
                    :avatar, :active, :role, :member_number, :email,
                    :date_of_joining, :password, :password_confirmation,
                    emergency_contact_attributes: [:id, :name, :email, :phone,
                    :additional_phone, :_destroy])
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<div class="row text-center">
  <img height="150" width="150" id="avatar" class="img-circle" src="<%= (@user.avatar.present? and !@user.avatar_updated_at_changed?)? @user.avatar.url(:medium) : asset_path('default-profile.jpg') %>">
  <p><small class="info">(Tamaño máximo de 5MB)</small></p>
</div>
<br>
<div class="input-group user-img image-preview text-center" style="width:30%;left:35%">
  <input type="text" class="form-control image-preview-filename" disabled="disabled">
  <span class="input-group-btn">
    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
      <span class="glyphicon glyphicon-remove"></span> Quitar
    </button>
    <div class="btn btn-default image-preview-input">
      <span class="glyphicon glyphicon-folder-open"></span>
      <span class="image-preview-input-title">Buscar</span>
      <%= f.file_field :avatar %>
    </div>
  </span>
</div>

<div class="form-group row" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :first_name, input_html: { class: 'form-control',
      placeholder: 'Nombre' }, required: true %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :last_name, input_html: { class: 'form-control',
      placeholder: 'Apellido' }, required: true %>
  </div>
</div>
<div class="form-group row" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :birthday, input_html: { class: 'form-control', data: {
      date_options: { format: 'DD/MM/YYYY' } } },
      required: true, as: :date_picker %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :gender, collection: User.genders.collect { |ct| [User.human_attribute_name("gender.#{ct[0]}"), ct[0]] },
      as: :radio_buttons, item_wrapper_class: 'inline', required: true %>
  </div>
</div>
<% if params[:action] != 'new' %>
<div class="form-group row" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :password, input_html: { class: 'form-control' } %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :password_confirmation, input_html: { class: 'form-control' } %>
  </div>
</div>
<% end %>
<div class="form-group row" style="padding:10px;margin:0">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= f.input :phone, input_html: { class: 'form-control',
      placeholder: '+569...' }, required: true %>
  </div>
</div>
<% if current_user.admin? %>
  <div class="form-group row" style="padding:10px;margin:0">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <%= f.input :active, collection: [['Activo', true],['Inactivo', false]],
        as: :radio_buttons, item_wrapper_class: 'inline', required: true %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <%= f.input :role, collection: User.roles.collect { |r| [t(r[0]), r[0]] },
        input_html: { class: 'form-control ctype' }, prompt: 'Tipo de usuario' %>
    </div>
  </div>
  <div class="form-group row" style="padding:10px;margin:0">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <%= f.input :member_number, input_html: { class: 'form-control',
        placeholder: 'Nombre' }, required: true %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <%= f.input :email, input_html: { class: 'form-control',
        placeholder: 'Apellido' }, required: true %>
    </div>
  </div>
  <div class="form-group row" style="padding:10px;margin:0">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <%= f.input :date_of_joining, input_html: { class: 'form-control', data: {
        date_options: { format: 'DD/MM/YYYY' } } },
        required: true, as: :date_picker %>
    </div>
  </div>
<% end %>
<h3>Contacto de emergencia</h3>
<div class="panel panel-default">
  <%= f.simple_fields_for :emergency_contact do |ec| %>
    <div class="form-group row multiple-form-group ecs" style="padding:10px;margin:0">
      <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
        <%= ec.input :name, input_html: { class: 'form-control name',
          placeholder: 'Nombre' }, label: false, required: true %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
        <%= ec.input :email, input_html: { class: 'form-control email',
          placeholder: 'Correo electrónico' }, label: false %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
        <%= ec.input :phone, input_html: { class: 'form-control phone',
          placeholder: 'Teléfono' }, label: false, required: true %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
        <%= ec.input :additional_phone, input_html: { class: 'form-control additional-phone',
          placeholder: 'Teléfono adicional' }, label: false %>
      </div>
    </div>
  <% end %>
</div>
<div class="form-actions row">
  <div class="col-md-5">
    <%= f.submit 'Guardar', class: 'btn btn-success' %>
  </div>
</div>

app/views/users/_trip_notice.html.erb
<tr class="tn-item-<%= t.id %>">
  <td><%= t.zone %></td>
  <td><%= t.route %></td>
  <td><%= l(t.updated_at, format: :def1) %></td>
  <td>
    <% t.participants.each_with_index do |p, index| %>
      <%= ', ' if index > 0 %>
      <%= link_to p.full_name2, user_path(p) %>
    <% end %>
  </td>
  <td id="send-btn-container">
    <%= 'Enviado' if t.sent? %>
    <%= link_to 'Enviar', 'javascript:void(0)', id: 'send-btn',
      class: 'btn btn-primary', 'data-tn-id': t.id if t.saved? %>
  </td>
  <td class="text-right">
    <%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i>'),
      trip_notice_path(t, request: 'preview'), target: '_blank', class: "btn btn-info",
      title: "Ver" %>
    <%= link_to raw('<i class="glyphicon glyphicon-download"></i>'),
      trip_notice_path(t, request: 'download'), class: "btn btn-success download",
      id: 'dwnl-btn', title: "Descargar", style: t.sent? ? '' : 'display: none' %>
    <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'),
      edit_trip_notice_path(t), title: "Editar", class: "btn btn-warning edit", style: t.saved? ? '' : 'display: none' %>
  </td>
</tr>

app/views/users/edit.html.erb
<%= link_to 'Atrás', :back, class: 'btn btn-default' %>
<h1>Editar Perfil</h1>

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= render 'form', f:f %>
<% end %>

app/views/users/index.html.erb
<%= link_to 'Nuevo Usuario', new_user_path,
  'data-turbolinks': false, class: 'btn btn-info pull-right' %>
<h1>Usuarios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo electrónico</th>
      <th>Rol</th>
      <th>Número socio</th>
      <th>Estado</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody id="trip-notices-list">
    <% @users.each do |u| %>
      <tr>
        <td><%= u.full_name %></td>
        <td><%= u.email %></td>
        <td><%= t(u.role) %></td>
        <td><%= u.member_number %></td>
        <td><%= u.active ? 'Activo' : 'Inactivo' %></td>
        </td>
        <td class="text-right">
          <%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i>'),
            user_path(u, request: 'preview'), class: "btn btn-info", title: "Ver" %>
          <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'),
            edit_user_path(u), title: "Editar", class: "btn btn-warning" %>
          <%= link_to raw('<i class="glyphicon glyphicon-trash"></i>'), user_path(u),
            class: "btn btn-danger", title: "Eliminar", method: :delete, data: { confirm: '¿Estás seguro?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/me.html.erb
<div class="row">
  <div class="board">
    <div class="board-inner">
      <ul style="margin:0" class="nav nav-tabs" id="myTab">
        <div class="liner"></div>
        <% if @current_user.member? || @current_user.admin?%>
          <li class="active">
            <a href="#profile" data-toggle="tab" title="Información de perfil">
              <span class="round-tabs one"><i class="glyphicon glyphicon-user"></i></span>
            </a>
          </li>
          <li>
            <a href="#medical_record" data-toggle="tab" title="Ficha médica">
              <span class="round-tabs two"><i class="fa fa-medkit"></i></span>
            </a>
          </li>
        <% end %>
        <% if @current_user.member? || @current_user.admin?%>
          <li>
        <%else%>
          <li class="active">
        <%end%>
          <a href="#trip_notices" data-toggle="tab" title="Avisos de salida">
            <span class="round-tabs three"><i class="glyphicon glyphicon-list-alt"></i></span>
          </a>
        </li>
      </ul>
    </div>
    <div class="tab-content">
    <% if @current_user.member? || @current_user.admin?%>
      <div class="tab-pane fade in active" id="profile">
        <div class="row">
          <div class="col-md-8 col-lg-8">
          	<div class="well profile" style="width:100%">
              <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                  <h2><%= @user.full_name2 %></h2>
                  <p><i class='glyphicon glyphicon-envelope'></i> <strong>Correo electrónico: </strong> <%= @user.email %> </p>
                  <p><i class='fa fa-intersex'></i> <strong>Género: </strong> <%= t(@user.gender) %> </p>
                  <p><i class='fa fa-blind'></i> <strong>Edad: </strong> <%= @user.age %> </p>
                  <p><i class='glyphicon glyphicon-ok'></i> <strong>Estado: </strong> <%= raw("<span class='text-success'>Activo</span>") if @user.active %> <%= raw("<span class='text-danger'>Inactivo</span>") unless @user.active %> </p>
                  <p><i class='fa fa-mobile-phone'></i> <strong>Teléfono: </strong> <%= @user.phone %> </p>
                  <p><i class='fa fa-database'></i> <strong>Número de socio: </strong> <%= @user.member_number %> </p>
                </div>
                <div class="col-xs-12 col-sm-4 text-center">
                  <%= link_to raw("<i class='fa fa-edit'></i>"), edit_user_path(@user),
                    'data-turbolinks': false, class: 'btn btn-info pull-right' %>
                  <figure>
                    <%= image_tag @user.image, class: 'img-circle img-responsive' %>
                    <figcaption class="ratings">
                      <p><%= t(@user.role) + ' ' + @user.seniority.to_s %><%= @user.date_of_joining.year == Date.current.year ? ' meses' : ' años' if @user.date_of_joining.present? %>
                      </p>
                    </figcaption>
                  </figure>
                </div>
              </div>
              <!-- <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                  <h2><strong> <%= @user.trip_notices.length %> </strong></h2>
                  <p><small>Salidas</small></p>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                  <h2><strong>Al día</strong></h2>
                  <p><small>Estado financiero</small></p>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                  <h2><strong>M2</strong></h2>
                  <p><small>Último nivel completado</small></p>
                </div>
              </div> -->
          	</div>
      		</div>
          <div class="col-md-4 col-lg-4">
          	 <div style="width:100%" class="well profile">
               <h3 style="margin-top:0">Contacto de emergencia</h3>
               <% if @user.emergency_contact.present? %>
                 <div class="col-sm-12">
                   <h4><%= @user.emergency_contact.name %></h4>
                 </div>
                 <div class="col-sm-11 col-sm-offset-1">
                   <p><%= raw("<i class='glyphicon glyphicon-envelope'></i> #{@user.emergency_contact.email}") %></p>
                   <p><%= raw("<i class='fa fa-mobile-phone'></i> #{@user.emergency_contact.phone}") %></p>
                   <p><%= raw("<i class='fa fa-mobile-phone'></i> #{@user.emergency_contact.additional_phone}") if @user.emergency_contact.additional_phone.present? %> </p>
                 </div>
               <% end %>
          	 </div>
      		</div>
        </div>
      </div>
      <div class="tab-pane fade" id="medical_record">
        <div class="row text-right">
          <%= link_to 'Editar', edit_medical_record_path,
            'data-turbolinks': false, class: 'btn btn-info' if @user.medical_record.present? %>
          <%= link_to 'Nueva Ficha Médica', new_medical_record_path,
            'data-turbolinks': false, class: 'btn btn-info' unless @user.medical_record.present? %>
        </div>
        <h2 class="text-center">Ficha médica</h2>
        <p style="color:#1fcaa7;font-weight:bold"><em>* A la ficha médica solo usted y los administradores del sistema tiene acceso.</em></p>
        <% if @user.medical_record.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>Tipo de sangre</th>
                <th>Previsión</th>
                <th>Seguro</th>
                <th>Centro médico de preferencia</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= t(@user.medical_record.blood_type) if @user.medical_record %></td>
                <td><%= @user.medical_record.medical_insurance if @user.medical_record %></td>
                <td><%= @user.medical_record.health_insurance if @user.medical_record %></td>
                <td><%= @user.medical_record.prefered_medical_center if @user.medical_record %></td>
              </tr>
            </tbody>
          </table>
          <br>
          <% if @user.medical_record.medical_conditions %>
            <h3>Condiciones médicas</h3>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Riesgo</th>
                  <th>Medicamento</th>
                  <th>Dosis/frecuencia</th>
                  <th>Efectos secundarios</th>
                  <th>Comentarios</th>
                </tr>
              </thead>
              <tbody>
                <% @user.medical_record.medical_conditions.each do |mc| %>
                  <tr>
                    <td><%= mc.name %></td>
                    <td><%= mc.risk %></td>
                    <td><%= mc.medicine %></td>
                    <td><%= mc.dose %></td>
                    <td><%= mc.side_effects %></td>
                    <td><%= mc.comment %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        <% else %>
          <p class="text-center">Actualmente no tiene una ficha médica</p>
        <% end %>
      </div>
      <div class="tab-pane fade" id="trip_notices">
      <%else%>
      <div class="tab-pane fade in active" id="trip_notices">
      <% end %>
        <div class="row text-right">
          <%= link_to 'Nuevo Aviso de Salida', new_trip_notice_path,
            'data-turbolinks': false, class: 'btn btn-info' %>
        </div>
        <h2 class="text-center">Avisos de salida</h2><br>
        <div class="row text-center">
          <div class="col col-md-6 col-md-offset-3">
            <div id="custom-search-input">
              <div class="input-group col-md-12">
                <input type="text" class="search-query form-control"
                       placeholder="Buscar por nombre de ruta o zona/cerro" />
                <span class="input-group-btn">
                  <button class="btn btn-danger" type="button">
                    <span class=" glyphicon glyphicon-search"></span>
                  </button>
                </span>
              </div>
            </div>
          </div>
        </div><br>
        <% if @trip_notices.present? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Zona</th>
              <th>Ruta</th>
              <th>Fecha última edición</th>
              <th>Participantes</th>
              <th>Estado</th>
              <th>Opciones</th>
            </tr>
          </thead>
          <tbody id="trip-notices-list">
            <% @trip_notices.each do |t| %>
              <%= render 'trip_notice', t:t %>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p class="text-center">Actualmente no tiene avisos de salida</p>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= link_to 'Atrás', :back, class: 'btn btn-default' %>
<h1>Nuevo Usuario</h1>

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= render 'form', f:f %>
<% end %>