config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    authenticated :user do
      root 'users#me', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :zones
  resources :routes
  resources :trip_notices, except: :index do
    get 'search', on: :collection
    get 'send_mail', on: :member
  end
  resources :users do
    collection do
      get 'me'
      resource :medical_record, path: 'me/medical_record'
    end
  end

end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
<footer>
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-md-7">
        Copyright &copy; <%= Date.current.year %> <span>Club Andino Universitario</span> | Contacto: <em><%= link_to 'contacto@cau.cl', 'mailto:contacto@cau.cl' %></em> | Social: <%= link_to raw("<i class='fa fa-facebook-square'></i>"), 'https://www.facebook.com/clubandinouniversitario', target: '_blank', class: 'fb' %>
      </div>
      <div class="col-xs-12 col-md-5">
        Desarrollado por <b>Francisco Vallés</b> y <b>Daniela Quiroz</b>
        <p class="small">*Errores y consultas a: <b>fjvallesj@gmail.com</b></p>
      </div>
    </div>
  </div>
</footer>
<% end %>

app/views/layouts/_menu.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to authenticated_root_path, class: 'navbar-brand' do %>
        <%= image_tag("logoCAU.png", height: '40') %>
        <b>Club Andino Universitario</b>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Usuarios', users_path if current_user.admin? %>
        </li>
        <li>
          <%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Aviso de salida"), new_trip_notice_path, 'data-turbolinks': false %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <b>Hola, <%= current_user.first_name.titleize %></b> <span class="glyphicon glyphicon-menu-down"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to raw("Mi Perfil <span class='glyphicon glyphicon-user pull-right'></span>"), me_users_path %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to raw("Cerrar sesión <span class='glyphicon glyphicon-log-out pull-right'></span>"), destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socios CAU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div id="notice"><%= bootstrap_flash %></div>
    <div class="container">
      <div style="display:none" class="alert alert-success"></div>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/log_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socios CAU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #ECF0F0;">
    <%= render "layouts/menu" %>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>